name: deep-hybrid-models
channels:
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - pytorch-cuda=12.4
  - torchaudio
  - torchvision
  - anaconda::numpy
  - anaconda::scipy
  - anaconda::scikit-learn
  - plotly::plotly
  - anaconda::pandas
  - pip:
      - matplotlib==3.10.0
      - tqdm==4.67.1
      - wandb==0.19.4
